name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: AndreaZavatta/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.c6a4c612-1188-446b-a37e-9b3b01d08c93 }}
          GH_TOKEN: ${{ secrets.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 }}
